import { createNanoIconSet } from 'react-native-nano-icons';
// Auto-generated by the react-native-nano-icons config plugin during prebuild
// from the SVGs in `assets/icons/svg`.
import glyphMap from '@/assets/icons/nanoicons/svg.glyphmap.json';

/**
 * Typed icon component backed by the bundled `svg` nano-icons font. Icon names
 * map 1:1 to the source SVG filenames in `assets/icons/svg`, e.g.
 * `<Icon name="chevron-right" size={24} />`.
 */
export const Icon = createNanoIconSet(glyphMap);
